export const userData = [
    {
        name: "Jan",
        "Active User": 1000,
    },
    {
        name: "Feb",
        "Active User": 1340,
    },
    {
        name: "Mar",
        "Active User": 2000,
    },
    {
        name: "Apr",
        "Active User": 1040,
    },
    {
        name: "May",
        "Active User": 3000,
    },
    {
        name: "Jun",
        "Active User": 4400,
    },
    {
        name: "Jul",
        "Active User": 3050,
    },
    {
        name: "Agu",
        "Active User": 200,
    },
    {
        name: "Sep",
        "Active User": 1000,
    },
    {
        name: "Oct",
        "Active User": 500,
    },
    {
        name: "Nov",
        "Active User": 1200,
    },
    {
        name: "Dec",
        "Active User": 4300,
    },
];

export const userRows = [
    {
        id: 1,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/5851184/pexels-photo-5851184.jpeg?cs=srgb&dl=pexels-billow-5851184.jpg&fm=jpg",
        email: "jon@gmail.com",
        status: "active",
        transaction: "$120.00",
    },
    {
        id: 2,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/5851184/pexels-photo-5851184.jpeg?cs=srgb&dl=pexels-billow-5851184.jpg&fm=jpg",
        email: "jon@gmail.com",
        status: "active",
        transaction: "$120.00",
    },
    {
        id: 3,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/5851184/pexels-photo-5851184.jpeg?cs=srgb&dl=pexels-billow-5851184.jpg&fm=jpg",
        email: "jon@gmail.com",
        status: "active",
        transaction: "$120.00",
    },
    {
        id: 4,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/5851184/pexels-photo-5851184.jpeg?cs=srgb&dl=pexels-billow-5851184.jpg&fm=jpg",
        email: "jon@gmail.com",
        status: "active",
        transaction: "$120.00",
    },
    {
        id: 5,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/5851184/pexels-photo-5851184.jpeg?cs=srgb&dl=pexels-billow-5851184.jpg&fm=jpg",
        email: "jon@gmail.com",
        status: "active",
        transaction: "$120.00",
    },
    {
        id: 6,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/5851184/pexels-photo-5851184.jpeg?cs=srgb&dl=pexels-billow-5851184.jpg&fm=jpg",
        email: "jon@gmail.com",
        status: "active",
        transaction: "$120.00",
    },
    {
        id: 7,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/5851184/pexels-photo-5851184.jpeg?cs=srgb&dl=pexels-billow-5851184.jpg&fm=jpg",
        email: "jon@gmail.com",
        status: "active",
        transaction: "$120.00",
    },
    {
        id: 8,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/5851184/pexels-photo-5851184.jpeg?cs=srgb&dl=pexels-billow-5851184.jpg&fm=jpg",
        email: "jon@gmail.com",
        status: "active",
        transaction: "$120.00",
    },
    {
        id: 9,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/5851184/pexels-photo-5851184.jpeg?cs=srgb&dl=pexels-billow-5851184.jpg&fm=jpg",
        email: "jon@gmail.com",
        status: "active",
        transaction: "$120.00",
    },
    {
        id: 10,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/5851184/pexels-photo-5851184.jpeg?cs=srgb&dl=pexels-billow-5851184.jpg&fm=jpg",
        email: "jon@gmail.com",
        status: "active",
        transaction: "$120.00",
    },
];

export const productRows = [
    {
        id: 1,
        name: "Apple Watch",
        img: "https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?cs=srgb&dl=pexels-torsten-dettlaff-437037.jpg&fm=jpg",
        stock: 123,
        status: "active",
        price: "$120.00",
    },
    {
        id: 2,
        name: "Apple Watch",
        img: "https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?cs=srgb&dl=pexels-torsten-dettlaff-437037.jpg&fm=jpg",
        stock: 123,
        status: "active",
        price: "$120.00",
    },
    {
        id: 3,
        name: "Apple Watch",
        img: "https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?cs=srgb&dl=pexels-torsten-dettlaff-437037.jpg&fm=jpg",
        stock: 123,
        status: "active",
        price: "$120.00",
    },
    {
        id: 4,
        name: "Apple Watch",
        img: "https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?cs=srgb&dl=pexels-torsten-dettlaff-437037.jpg&fm=jpg",
        stock: 123,
        status: "active",
        price: "$120.00",
    },
    {
        id: 5,
        name: "Apple Watch",
        img: "https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?cs=srgb&dl=pexels-torsten-dettlaff-437037.jpg&fm=jpg",
        stock: 123,
        status: "active",
        price: "$120.00",
    },
    {
        id: 6,
        name: "Apple Watch",
        img: "https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?cs=srgb&dl=pexels-torsten-dettlaff-437037.jpg&fm=jpg",
        stock: 123,
        status: "active",
        price: "$120.00",
    },
    {
        id: 7,
        name: "Apple Watch",
        img: "https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?cs=srgb&dl=pexels-torsten-dettlaff-437037.jpg&fm=jpg",
        stock: 123,
        status: "active",
        price: "$120.00",
    },
    {
        id: 8,
        name: "Apple Watch",
        img: "https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?cs=srgb&dl=pexels-torsten-dettlaff-437037.jpg&fm=jpg",
        stock: 123,
        status: "active",
        price: "$120.00",
    },
    {
        id: 9,
        name: "Apple Watch",
        img: "https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?cs=srgb&dl=pexels-torsten-dettlaff-437037.jpg&fm=jpg",
        stock: 123,
        status: "active",
        price: "$120.00",
    },
    {
        id: 10,
        name: "Apple Watch",
        img: "https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?cs=srgb&dl=pexels-torsten-dettlaff-437037.jpg&fm=jpg",
        stock: 123,
        status: "active",
        price: "$120.00",
    },
];
